import {
  Zap,
  Smartphone,
  Wallet,
  RefreshCw,
  Layers,
  MousePointerClick,
  Sparkles,
  Search,
  Accessibility,
  TrendingUp,
  Users,
  CreditCard,
  Utensils,
  ShoppingCart,
  ShoppingBag,
  Car,
  Wrench,
  Target,
  Lightbulb,
  LayoutTemplate,
  CheckCircle2,
  Hammer,
  BarChart3,
  PlayCircle,
  MessageCircleOff,
  type LucideIcon,
} from "lucide-react";

export const featureIconMap: Record<string, LucideIcon> = {
  zap: Zap,
  smartphone: Smartphone,
  wallet: Wallet,
  "refresh-cw": RefreshCw,
  layers: Layers,
  "mouse-pointer-click": MousePointerClick,
  sparkles: Sparkles,
  search: Search,
  accessibility: Accessibility,
  "trending-up": TrendingUp,
  users: Users,
  "credit-card": CreditCard,
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  car: Car,
  wrench: Wrench,
  target: Target,
  lightbulb: Lightbulb,
  "layout-template": LayoutTemplate,
  "check-circle": CheckCircle2,
  hammer: Hammer,
  "bar-chart": BarChart3,
  "play-circle": PlayCircle,
  "message-circle-off": MessageCircleOff,
};
